# Generated by Django 4.1.3 on 2023-07-07 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('qrcode', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evenement',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(related_name='guests', to='websnapbook.event')),
            ],
            options={
                'verbose_name': 'Invité',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websnapbook.event')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_photos', to='websnapbook.guest')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websnapbook.guest')),
            ],
            options={
                'verbose_name': 'Photo',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websnapbook.guest')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websnapbook.photo')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ('commented_at',),
            },
        ),
    ]
