# Generated by Django 4.1.3 on 2023-06-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websnapbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
