# Generated by Django 4.1.3 on 2023-06-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websnapbook', '0002_guest_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
