version: '3.7'

services:
   django_gunicorn:
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ../database/:/app/database
    env_file:
      - .env
    build:
      context: .
    ports:
      - 8000:8000
   nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ../nginx/conf/:/etc/nginx/conf.d/:ro
      - ../certbot/www/:/var/www/certbot/:ro
      - ../certbot/conf/:/etc/nginx/ssl/:ro

    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - django_gunicorn

   certbot:
    image: certbot/certbot:arm64v8-latest
    volumes:
      - ../certbot/www/:/var/www/certbot/:rw
      - ../certbot/conf/:/etc/letsencrypt/:rw
      - ../certbot/conf/log/:/var/log/letsencrypt/:rw
    depends_on:
      - nginx
      - django_gunicorn

volumes:
  static_volume:
  media_volume:
  