# Generated by Django 4.1.3 on 2022-12-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(default=1, max_length=200, verbose_name='Url de la page du projet'),
            preserve_default=False,
        ),
    ]
