# Generated by Django 3.0 on 2022-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Photo de profil')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Bannière')),
                ('sub_title', models.CharField(max_length=256)),
                ('resume', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1500)),
                ('description_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='Url')),
                ('description_img', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Description photo')),
                ('footer_text', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
    ]
