# Generated by Django 4.1.3 on 2022-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_profil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='github_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='profil',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='profil',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sub_title',
            field=models.CharField(max_length=80),
        ),
    ]
