# Generated by Django 4.1.3 on 2022-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_profil_github_url_profil_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='custom_url',
            field=models.SlugField(default=0, max_length=200, unique=True, verbose_name='Url de la page'),
            preserve_default=False,
        ),
    ]
