# Generated by Django 4.1.3 on 2022-12-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_profil_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='banner',
            field=models.ImageField(blank=True, default='static/img/default_banner.png', null=True, upload_to='profil/', verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='description_img',
            field=models.ImageField(blank=True, default='static/default_img.png', null=True, upload_to='profil/', verbose_name='Description photo'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/default_profil.png', null=True, upload_to='profil/', verbose_name='Photo de profil'),
        ),
    ]
