# Generated by Django 4.1.3 on 2022-12-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_profil_banner_alter_profil_description_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='description_img',
            field=models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Description photo'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Photo de profil'),
        ),
    ]
